---

- name: Copy templated blazegraph config files
  template:
    src: "{{ item }}"
    dest: "{{ blazegraph_RWStore_path }}{{ item }}"
    owner: "{{ blazegraph_user }}"
    group: "{{ blazegraph_user }}"
  with_items:
    - RWStore.properties
  notify: restart tomcat8

- name: Copy blazegraph config files
  copy:
    src: "{{ item }}"
    dest: "{{ blazegraph_home_dir }}/conf/{{ item }}"
    owner: "{{ blazegraph_user }}"
    group: "{{ blazegraph_user }}"
  with_items:
    - blazegraph.properties
    - inference.nt
  notify: restart tomcat8
