---

- name: Setup namespace in blazegraph
  command:
    curl -v -X POST -H 'Content-Type:text/plain' --data-binary @blazegraph.properties http://localhost:8080/bigdata/namespace
  args:
    chdir: "{{ blazegraph_home_dir }}/conf"
    warn: no
  when: blazegraph_war_download.changed is defined and blazegraph_war_download.changed

- name: Setup inference in blazegraph
  command:
    curl -v -X POST -H 'Content-Type:text/plain' --data-binary @inference.nt http://localhost:8080/bigdata/namespace/islandora/sparql
  args:
    chdir: "{{ blazegraph_home_dir }}/conf"
    warn: no
  when: blazegraph_war_download.changed is defined and blazegraph_war_download.changed
